//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ankurEntities : DbContext
    {
        public ankurEntities()
            : base("name=ankurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Amenity> Amenity { get; set; }
        public DbSet<Bidding> Bidding { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Flat> Flat { get; set; }
        public DbSet<Land> Land { get; set; }
        public DbSet<Locality> Locality { get; set; }
        public DbSet<Login> Login { get; set; }
        public DbSet<Trending> Trending { get; set; }
    }
}
