//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public Locality()
        {
            this.Flat = new HashSet<Flat>();
            this.Lands = new HashSet<Land>();
        }
    
        public int LocalityId { get; set; }
        public string LocalityName { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Flat> Flat { get; set; }
        public virtual ICollection<Land> Lands { get; set; }
    }
}
