//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trending
    {
        public int Id { get; set; }
        public int LocalityId { get; set; }
        public int Sales { get; set; }
        public int AmenitiesAvailable { get; set; }
        public int Security { get; set; }
        public int RatingScore { get; set; }
    }
}
